import turtle as t
# def goToEgypt():
#     t.speed('fastest')
#     t.color('gold')
#     t.begin_fill()
#     sq = 5
#     t. pensize(2)

#     #Draw a pyramid
#     for i in range (30):
#         t.forward(sq)
#         t.right(90)
#         t.forward(sq)
#         t.right(90)
#         t.color('gray')
#         t.forward(sq)
#         t.right(90)
#         t.color('gold')
#         t.forward(sq)
#         t.right(90)
#         sq += 5

#     t.color('white')
#     t.goto(-200,0)
#     t.color('gold')
#     sq = 5
#     for i in range (30):
#         t.forward(sq)
#         t.right(90)
#         t.forward(sq)
#         t.right(90)
#         t.color('gray')
#         t.forward(sq)
#         t.right(90)
#         t.color('gold')
#         t.forward(sq)
#         t.right(90)
#         sq += 5

#     t.color('white')
#     t.goto(0,-200)
#     t.color('gold')
#     sq = 5

#     for i in range (30):
#         t.forward(sq)
#         t.right(90)
#         t.forward(sq)
#         t.right(90)
#         t.color('gray')
#         t.forward(sq)
#         t.color('gold')
#         t.right(90)
#         t.forward(sq)
#         t.right(90)
#         sq += 5


#     t.color('white')
#     t.goto(-200,0)
#     t.goto(-200,200)
#     t.goto(150,200)
#     t.pensize(2)
#     t.color("gold")
#     t.begin_fill()
#     t.circle(50)
#     t.end_fill()
#     t.color('white')
#     t.goto(150,200)
#     t.pensize(2)
#     t.color("gold")
#     t.right(90)
#     t.forward(100)
#     t.color("gold")
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.backward(100)
#     t.right(15)
#     t.forward(145)
#     t.backward(145)
#     t.right(15)
#     t.forward(100)
#     t.color('white')

#     t.mainloop()

# def goToParis():
#     t.speed('fastest')
#     t.color('white')
#     t.begin_fill()
#     t. pensize(2)

#     t.goto(-100,-300)
#     t.color('brown')
#     t.left(85)
#     t.forward(200)
#     t.left(95)
#     t.forward(20)
#     t.right(90)
#     t.forward(30)
#     t.right(90)
#     t.forward(150)
#     t.right(90)
#     t.forward(30)
#     t.right(90)
#     t.forward(130)

#     t.right(95)
#     t.forward(150)
#     t.left(95)
#     t.forward(20)
#     t.right(90)
#     t.forward(30)
#     t.right(90)
#     t.forward(120)
#     t.right(90)
#     t.forward(30)
#     t.right(90)
#     t.forward(110)

#     t.mainloop()




# choice = int(input("Where do you want to go? \nEnter 1 for Egypt\nEnter 2 for Paris\nEnter 3 for The Amazon\n"))
# if choice == 1:
#     goToEgypt()
# elif choice == 2:
#     goToParis()
# elif choice ==3:
#     goToAmazon()
# else:
#     print("Please enter a correct number.")

word = str(input('word'))
wordLen = len(word)
lsWord = [word]

t.circle(120, 180)  # draw a semicircle
t.position()
t.heading()

t.write(str(lsWord[3]), font=("Arial", 36, "normal"))

#draw spaces for word chosen
# for i in range(wordLen):
    
#     t.fd(30)
#     t.penup()
#     t.fd(30)
#     t.pendown()

t.mainloop()
